### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by pdey** [andrebeat/rust-okasaki#2]
Hi Andre.
I was thinking of learning RUST by implementing Okasaki's Purely Functional Data Structures and found this repository. 

I am curious if you have done any performance comparison done against other (standard) implementation of the data structures.

Thanks,
pdey

**Comment by andresilva** [comment]
Sorry to have taken this long to reply. I also implemented these data structures when starting to learn Rust, which in my opinion is probably not the best way to start. I didn't do any performance analysis, but I'd expect these to be considerably slower than similar ones from the standard library since there's a lot of indirection.
